async function abc(letter)
{
    try{
        let c = await efg();
        if(!c)
            return 3
        throw new Error(e)
    }catch(e){
        throw new Error(e)
    }
}

//async function fonctionnement??